### ISSUE TITLE
remove the artist keyword

### ISSUE THREAD

**Issue by momoleomihara** [pharmapsychotic/clip-interrogator#37]
hi
is there any way to remove the artist name from the generated title

**Comment by momoleomihara** [comment]
I don't know the code, can you make it simple?

**Comment by mediocreatmybest** [comment]
I won't pretend this isn't hacky but it works for me. 
A temp fork: 
https://github.com/mediocreatmybest/clip-interrogator/tree/modified_dev
Most of my changes are on the run_cli.py file.
Also switched BLIP to offload by default otherwise I'm chewing out more than 16GB of vRAM. 

Added some options that exist on the config functions but aren't called in the default run_cli.py. 
Also added standard text captions as well as the original csv. 

Results may vary.

**Comment by mediocreatmybest** [comment]
> hi is there any way to remove the artist name from the generated title

Just did an update to stop the loading of the tables, seems to make it a little faster for me.
Anyway, as mentioned it seems to work for me.  I've only test best options so far.

**Comment by Seedmanc** [comment]
Although you can remove the artists.txt from the list of merged tables, there's a significant leakage of artist names into the flavors.txt file. I removed the duplicate entries in my version of the file, here: https://github.com/Seedmanc/clip-interrogator-average/blob/main/clip_interrogator/data/flavors.txt
