### ISSUE TITLE
The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0

### ISSUE THREAD

**Issue by VictorGalu** [pharmapsychotic/clip-interrogator#62]
Hello! I can't start interogator-ext. Startup stops with "Exception <class 'RuntimeError'>". This error falls in the thread title, Internal CLIP and DeepBooru work. Can anyone help with this problem?

**Comment by linqingfeng** [comment]
If the transformers version is greater than 4.27, this error will be triggered. Downgrading the transformers version to 4.26.1 can fix this error. I don’t know the specific reason, but this method works for me.

pip3 install transformers==4.26.1

**Comment by Vigilence** [comment]
> If the transformers version is greater than 4.27, this error will be triggered. Downgrading the transformers version to 4.26.1 can fix this error. I don’t know the specific reason, but this method works for me.
> 
> pip3 install transformers==4.26.1

If this is true, then maybe the coflict is due to the dreambooth extension which installs 4.27.1

Dreambooth's requirement.txt
`accelerate==0.17.1
albumentations~=1.3.0
bitsandbytes==0.35.4
dadaptation==1.5.0
diffusers~=0.14.0
discord-webhook~=1.1.0
fastapi~=0.90.1
ftfy~=6.1.1
gitpython~=3.1.31
lion-pytorch~=0.0.7
mediapipe-silicon; sys_platform == 'darwin'
mediapipe; sys_platform != 'darwin'
modelcards~=0.1.6
tensorboard~=2.11.2
tensorflow==2.11.0; sys_platform != 'darwin' or platform_machine != 'arm64'
tensorflow-macos==2.11.0; sys_platform == 'darwin' and platform_machine == 'arm64'
tqdm~=4.64.1
transformers~=4.27.1`

**Comment by dnwalkup** [comment]
> 

@linqingfeng nailed it, thank you!

**Comment by VictorGalu** [comment]
Thanks!

**Comment by rmpku** [comment]
The same error, update clip-interrogator==0.5.4 to clip-interrogator==0.6.0, it's works for me.

**Comment by pharmapsychotic** [comment]
Yes sorry the regular install of auto1111 webui uses one version of transformers and the dreambooth extension installs a different version and they need different versions of clip-interrogator. there may be some way for clip-interrogator to check what transformers is installed and manage to support both but I haven't had an opportunity to sort that out yet.
